### ISSUE TITLE
Evaluation of results

### ISSUE THREAD

**Issue by DirkOlten** [HSZemi/mahlowat#1]
Hi

First of all:
I'm very happy you made this script. It saved me a lot of time and it's working excellent.

One question remains:
Is there any way to get statistics out of the user inputs?
I found the two files salt.sav and visits.sav in folder /data/

Ist there any way to retrieve (anonymously) statistics from these files?

DirkO

**Comment by MarenMau** [comment]
Did you find out about it? I would like to find out about it as well.
However, I do not even have files in my data folder, it seems to remain empty.

**Comment by HSZemi** [comment]
I do not understand why github did not send me a notification for this issue, but here we are. I am sorry for the very late response.

The `admin/stats.php` page gives you very rough usage statistics as well as a raw list of stored answers (only of people who said *yes* to storing their answers).

If you do not have the `.sav` files in your `data` folder, the folder is probably not writable for the web server. Try giving it suitable permissions. It should definitely with permissions 777 (that is read, write, execute for user, group and all).
