### ISSUE TITLE
Feature Proposal: Multilingual Landing Page, Statistics, and More

### ISSUE THREAD

**Issue by SilvanVerhoeven** [HSZemi/mahlowat#15]
Heyho,

we've used mahlowat at our university for two years now. This year, I extended the feature set. I've added:

- a landing page to showcase the available languages
- anonymous usage statistics
- call to actions (like a button with "request postal vote now") at the end
- branding (logo and link to an organisation)

I've also improved the UX in `generator.html` a bit (to my eyes).

Since I wanted to preserve the features for following years and let others profit from them, I forked the repo and made them accessible via an own `setup.html` (basically a `generator.html` for all the new features).

Now I am unsure how to proceed: should mahlowat be "updated" to receive these features (they demand quite some changes to the current structure) or should both repos co-exist?

Check out #14 to see the changes.

Thanks a lot for providing mahlowat, it is a very nice software!

**Comment by HSZemi** [comment]
Those seem like nice additions. However, I think that your modifications make the whole setup a lot more complicated, especially for simple one-language deployments. And I have already seen quite a few people struggle with the setup in its current form.

Therefore, I think the best way to go ahead will be to keep Mahlowat in its simple state, and have people use Vote-O-mat if they with to use the additional features it provides.

**Comment by SilvanVerhoeven** [comment]
Understandable. I totally agree with you that the complexity increases.
If you don't mind, I'd open another PR that references Vote-O-Mat in the README, as Vote-O-Mat does with mahlowat. That way, people can find their best fitting solution more easily.
