### ISSUE TITLE
design customization

### ISSUE THREAD

**Issue by SpiGAndromeda** [HSZemi/mahlowat#2]
Hi,

do you plan to realize the possibility to change some aspects of the design by using the config file or by using an additional css (without using "!important") file?

**Comment by HSZemi** [comment]
There is no design modification via config file planned.

You should already be able to add your own style at the end of the head section in `index.html`, either inline or as an additional css file. No `!important` needed.
Also, you can switch out the base bootstrap theme (`css/bootstrap.min.css`), for example with a [Bootswatch](https://bootswatch.com/) one.
