### ISSUE TITLE
generator.html läd die bestehende data.config nicht

### ISSUE THREAD

**Issue by jlause** [HSZemi/mahlowat#20]
Hallo!

Erstmal danke für dieses tolle Projekt! Ich habe allerdings folgendes Problem:
In der Readme steht

> Falls bereits eine Konfigurationsdatei existiert, werden deren Inhalte direkt geladen. Für Korrekturen oder das Hinzufügen von Inhalten muss also nicht immer von vorn begonnen werden.

Das funktioniert bei mir leider nicht - obwohl sich bei mir unter `config/data.json` die richtige Datei liegt.

Wuerde mich ueber einen Hinweis freuen, woran das liegen koennte!

**Comment by HSZemi** [comment]
Der Generator funktioniert nur, wenn er von einem Webserver aus aufgerufen wird.
Früher™ konnte man ihn noch direkt in einem Webbrowser öffnen und die vorhandene `data.json` laden. Heutige Webbrowser lassen dies nicht mehr zu.
Ich werde die README-Dateien entsprechend ergänzen. Danke für den Hinweis.
