### ISSUE TITLE
Swiping with the mouse skips a these

### ISSUE THREAD

**Issue by Werninator** [HSZemi/mahlowat#3]
click + drag

**Comment by HSZemi** [comment]
I did a quick test and was not able to reproduce the issue.
- Which web browser does the issue appear in?
- Is the issue reproducible or does it happen randomly?
- Which thesis is skipped? is it always the same thesis?
- Does it happen in the sample installations (see README) or only in your local setup?

**Comment by Werninator** [comment]
* Chrome Version 70.0.3538.110 (64-Bit)
* macOS 10.14 (18A391)
* Used Demo: https://hscmi.de/mahlowat/de/

I could reproduce it by restarting the quiz, probably the "swipe" event handler gets applied after clicking the "Mahlowat starten!" Button. After each restart, you will skip one more page with a swipe.

**Comment by HSZemi** [comment]
Yes, this seems to be the issue. I was able to reproduce it as well.

**Comment by HSZemi** [comment]
Thank you very much for your detailed bug report. I have been able to resolve the issue.
