### ISSUE TITLE
IE11 errors

### ISSUE THREAD

**Issue by hoverlord** [HSZemi/mahlowat#4]
Hi! When I open the [demo installation](https://hscmi.de/mahlowat/de/) with Internet Explorer 11 it is not working, I only see the variable names like "start-explanatory-text". In console, 2 errors are shown: syntax error in de_de.js and Expected ';' in mahlowat.js, Line 313

**Comment by HSZemi** [comment]
Unfortunately, I do not have an IE 11 available to reproduce your issue.
If you can provide me with a pull request that fixes the issue for IE 11 and does not break functionality for major web browsers, I will gladly integrate it.

**Comment by Werninator** [comment]
There are two errors that came up and there were probably more. 

* the class keyword is not supported (language file de_de.js for example)
* the for-of loop is not supported

It comes down to the problem of using modern JavaScript functionalities. One simple solution would be to use the [babel compiler](https://babeljs.io/) to compile these into usable code for older browsers without changing the logic in itself.

I ran babel on mahlowat.js and de_de.js and it works perfectly now. It still works on modern browsers on my Mac (Chrome, Firefox, Safari).

**Comment by HSZemi** [comment]
I adjusted the for-loop in `mahlowat.js` and ran babel on the translation files. Thank you for the suggestion, @Werninator !
@hoverlord , can you confirm that it works for you now as well?

**Comment by hoverlord** [comment]
Its working fine now, thanks a lot @Werninator and @HSZemi !
